POST http://localhost:8080/test/testEnum
Content-Type: application/json

{
  "state": 1
}

###
POST http://localhost:8080/test/testListReq
Content-Type: application/json

[{"id": 1, "name":  "任务一"}, {"id": 2, "name":  "任务二"}]

###
GET http://localhost:8080/user/list

###
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "name": "哈哈",
  "sex": 1
}

###
POST http://localhost:8080/testEntity/post
Content-Type: application/json

{
  "name": "ss",
  "sex": 2
}